
-- Remove existing fake data and replace with real Project Gutenberg books
DELETE FROM public_domain_books;

-- Insert real Project Gutenberg books that have verified covers and EPUB files
INSERT INTO public_domain_books (id, title, author, subjects, cover_url, epub_url, gutenberg_id, description, language, last_updated, created_at) VALUES
('gutenberg-1342', 'Pride and Prejudice', 'Jane Austen', ARRAY['fiction', 'romance', 'classic literature'], 'https://www.gutenberg.org/cache/epub/1342/pg1342.cover.medium.jpg', 'https://www.gutenberg.org/ebooks/1342.epub.noimages', 1342, 'A classic novel about Elizabeth Bennet and her complex relationship with the proud Mr. Darcy.', 'en', NOW(), NOW()),
('gutenberg-11', 'Alice''s Adventures in Wonderland', 'Lewis Carroll', ARRAY['fiction', 'fantasy', 'children''s literature'], 'https://www.gutenberg.org/cache/epub/11/pg11.cover.medium.jpg', 'https://www.gutenberg.org/ebooks/11.epub.noimages', 11, 'The timeless tale of Alice''s journey through Wonderland.', 'en', NOW(), NOW()),
('gutenberg-84', 'Frankenstein; Or, The Modern Prometheus', 'Mary Wollstonecraft Shelley', ARRAY['fiction', 'horror', 'science fiction'], 'https://www.gutenberg.org/cache/epub/84/pg84.cover.medium.jpg', 'https://www.gutenberg.org/ebooks/84.epub.noimages', 84, 'The classic tale of Victor Frankenstein and his creation.', 'en', NOW(), NOW()),
('gutenberg-74', 'The Adventures of Tom Sawyer', 'Mark Twain', ARRAY['fiction', 'adventure', 'children''s literature'], 'https://www.gutenberg.org/cache/epub/74/pg74.cover.medium.jpg', 'https://www.gutenberg.org/ebooks/74.epub.noimages', 74, 'The adventures of a young boy growing up along the Mississippi River.', 'en', NOW(), NOW()),
('gutenberg-1661', 'The Adventures of Sherlock Holmes', 'Arthur Conan Doyle', ARRAY['fiction', 'mystery', 'detective'], 'https://www.gutenberg.org/cache/epub/1661/pg1661.cover.medium.jpg', 'https://www.gutenberg.org/ebooks/1661.epub.noimages', 1661, 'A collection of twelve short stories featuring the famous detective Sherlock Holmes.', 'en', NOW(), NOW()),
('gutenberg-2701', 'Moby Dick; Or, The Whale', 'Herman Melville', ARRAY['fiction', 'adventure', 'classic literature'], 'https://www.gutenberg.org/cache/epub/2701/pg2701.cover.medium.jpg', 'https://www.gutenberg.org/ebooks/2701.epub.noimages', 2701, 'The epic tale of Captain Ahab''s obsessive quest for the white whale.', 'en', NOW(), NOW()),
('gutenberg-1260', 'Jane Eyre: An Autobiography', 'Charlotte Brontë', ARRAY['fiction', 'romance', 'classic literature'], 'https://www.gutenberg.org/cache/epub/1260/pg1260.cover.medium.jpg', 'https://www.gutenberg.org/ebooks/1260.epub.noimages', 1260, 'The story of an orphaned girl who becomes a governess and finds love.', 'en', NOW(), NOW()),
('gutenberg-145', 'Middlemarch', 'George Eliot', ARRAY['fiction', 'classic literature', 'social commentary'], 'https://www.gutenberg.org/cache/epub/145/pg145.cover.medium.jpg', 'https://www.gutenberg.org/ebooks/145.epub.noimages', 145, 'A complex tale of idealism, disillusion, and the social fabric of a provincial town.', 'en', NOW(), NOW()),
('gutenberg-16', 'Peter Pan', 'J. M. Barrie', ARRAY['fiction', 'fantasy', 'children''s literature'], 'https://www.gutenberg.org/cache/epub/16/pg16.cover.medium.jpg', 'https://www.gutenberg.org/ebooks/16.epub.noimages', 16, 'The magical story of the boy who wouldn''t grow up and his adventures in Neverland.', 'en', NOW(), NOW()),
('gutenberg-98', 'A Tale of Two Cities', 'Charles Dickens', ARRAY['fiction', 'historical', 'classic literature'], 'https://www.gutenberg.org/cache/epub/98/pg98.cover.medium.jpg', 'https://www.gutenberg.org/ebooks/98.epub.noimages', 98, 'Set during the French Revolution, this novel explores themes of sacrifice and redemption.', 'en', NOW(), NOW())
ON CONFLICT (gutenberg_id) DO NOTHING;
