/**
 * Stripe Price ID Configuration
 * 
 * IMPORTANT: These Price IDs are generated by the setup-stripe.ts script
 * Run the script and update these values with the output
 * 
 * Script location: scripts/setup-stripe.ts
 * Run command: cd scripts && npm run setup
 */

export const STRIPE_PRICE_IDS = {
  // AI Coach Basic (500 credits/month)
  AI_COACH_BASIC_MONTHLY: 'price_REPLACE_WITH_BASIC_MONTHLY',
  AI_COACH_BASIC_ANNUAL: 'price_REPLACE_WITH_BASIC_ANNUAL',
  
  // AI Coach Pro (2500 credits/month)
  AI_COACH_PRO_MONTHLY: 'price_REPLACE_WITH_PRO_MONTHLY',
  AI_COACH_PRO_ANNUAL: 'price_REPLACE_WITH_PRO_ANNUAL',
  
  // AI Coach Pro+ (5000 credits/month)
  AI_COACH_PRO_PLUS_MONTHLY: 'price_REPLACE_WITH_PRO_PLUS_MONTHLY',
  AI_COACH_PRO_PLUS_ANNUAL: 'price_REPLACE_WITH_PRO_PLUS_ANNUAL',
  
  // One-time credit pack (500 credits)
  AI_CREDIT_PACK: 'price_REPLACE_WITH_CREDIT_PACK'
} as const;

/**
 * Tier to Price mapping with credit information
 * Used by create-checkout edge function
 */
export const TIER_TO_PRICE_MAP = {
  basic: {
    monthly: STRIPE_PRICE_IDS.AI_COACH_BASIC_MONTHLY,
    annual: STRIPE_PRICE_IDS.AI_COACH_BASIC_ANNUAL,
    credits: 500,
    name: 'AI Coach Basic',
    display_price_monthly: '$4.99',
    display_price_annual: '$49'
  },
  pro: {
    monthly: STRIPE_PRICE_IDS.AI_COACH_PRO_MONTHLY,
    annual: STRIPE_PRICE_IDS.AI_COACH_PRO_ANNUAL,
    credits: 2500,
    name: 'AI Coach Pro',
    display_price_monthly: '$19',
    display_price_annual: '$199'
  },
  pro_plus: {
    monthly: STRIPE_PRICE_IDS.AI_COACH_PRO_PLUS_MONTHLY,
    annual: STRIPE_PRICE_IDS.AI_COACH_PRO_PLUS_ANNUAL,
    credits: 5000,
    name: 'AI Coach Pro+',
    display_price_monthly: '$29',
    display_price_annual: '$299'
  },
  credit_pack: {
    one_time: STRIPE_PRICE_IDS.AI_CREDIT_PACK,
    credits: 500,
    name: 'AI Credit Pack',
    display_price: '$5'
  }
} as const;

/**
 * Type definitions for type safety
 */
export type SubscriptionTier = 'basic' | 'pro' | 'pro_plus';
export type BillingInterval = 'monthly' | 'annual';
export type ProductType = SubscriptionTier | 'credit_pack';

/**
 * Validate that all Price IDs have been replaced
 */
export function validatePriceIds(): boolean {
  const allIds = Object.values(STRIPE_PRICE_IDS);
  const hasPlaceholders = allIds.some(id => id.includes('REPLACE'));
  
  if (hasPlaceholders) {
    console.error('❌ Stripe Price IDs not configured!');
    console.error('   Run: cd scripts && npm run setup');
    console.error('   Then update supabase/functions/_shared/stripe-config.ts');
    return false;
  }
  
  return true;
}

/**
 * Get price ID for a given tier and interval
 */
export function getPriceId(
  tier: SubscriptionTier, 
  interval: BillingInterval
): string {
  const config = TIER_TO_PRICE_MAP[tier];
  return interval === 'annual' ? config.annual : config.monthly;
}

/**
 * Get credit pack price ID
 */
export function getCreditPackPriceId(): string {
  return TIER_TO_PRICE_MAP.credit_pack.one_time;
}
