/**
 * Stripe Price ID Configuration
 * 
 * Generated by: scripts/setup-stripe.ts
 * Updated: 2025-01-XX with production Price IDs
 */

// AI Coach Basic (500 credits/month)
export const AI_COACH_BASIC_MONTHLY = "price_1SHrqdAKVCfeyoX0rlhUrkQ7";
export const AI_COACH_BASIC_ANNUAL = "price_1SHrpeAKVCfeyoX06UoOkFM4";

// AI Coach Pro (2500 credits/month)
export const AI_COACH_PRO_MONTHLY = "price_1SHrt6AKVCfeyoX0zGA4hLT5";
export const AI_COACH_PRO_ANNUAL = "price_1SHrtlAKVCfeyoX0hVj9w324";

// AI Coach Pro+ (5000 credits/month)
export const AI_COACH_PRO_PLUS_MONTHLY = "price_1SHrwuAKVCfeyoX0jeTRonfn";
export const AI_COACH_PRO_PLUS_ANNUAL = "price_1SHrxiAKVCfeyoX0GnSJSKC6";

// One-time credit pack (500 credits)
export const AI_CREDIT_PACK = "price_1SHrvRAKVCfeyoX08HYb7fnO";

/**
 * Tier to Price mapping with credit information
 * Used by create-checkout edge function
 */
export const TIER_TO_PRICE_MAP = {
  basic: {
    monthly: AI_COACH_BASIC_MONTHLY,
    annual: AI_COACH_BASIC_ANNUAL,
    credits: 500,
    name: 'AI Coach Basic',
    display_price_monthly: '$4.99',
    display_price_annual: '$49'
  },
  pro: {
    monthly: AI_COACH_PRO_MONTHLY,
    annual: AI_COACH_PRO_ANNUAL,
    credits: 2500,
    name: 'AI Coach Pro',
    display_price_monthly: '$19',
    display_price_annual: '$199'
  },
  pro_plus: {
    monthly: AI_COACH_PRO_PLUS_MONTHLY,
    annual: AI_COACH_PRO_PLUS_ANNUAL,
    credits: 5000,
    name: 'AI Coach Pro+',
    display_price_monthly: '$29',
    display_price_annual: '$299'
  },
  credit_pack: {
    one_time: AI_CREDIT_PACK,
    credits: 500,
    name: 'AI Credit Pack',
    display_price: '$5'
  }
} as const;

/**
 * Type definitions for type safety
 */
export type SubscriptionTier = 'basic' | 'pro' | 'pro_plus';
export type BillingInterval = 'monthly' | 'annual';
export type ProductType = SubscriptionTier | 'credit_pack';

/**
 * Get price ID for a given tier and interval
 */
export function getPriceId(
  tier: SubscriptionTier, 
  interval: BillingInterval
): string {
  const config = TIER_TO_PRICE_MAP[tier as keyof typeof TIER_TO_PRICE_MAP];
  if (!config || !('monthly' in config)) {
    throw new Error(`Invalid tier: ${tier}`);
  }
  return interval === 'annual' ? config.annual : config.monthly;
}

/**
 * Get credit pack price ID
 */
export function getCreditPackPriceId(): string {
  return TIER_TO_PRICE_MAP.credit_pack.one_time;
}
