import { Sparkles } from "lucide-react";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Badge } from "@/components/ui/badge";

interface AIAttributionProps {
  variant?: 'badge' | 'icon';
  className?: string;
}

export const AIAttribution = ({ variant = 'badge', className = '' }: AIAttributionProps) => {
  const tooltipText = "This content was generated by the FPX AI assistant based on the data in your account. Please review for accuracy.";

  if (variant === 'badge') {
    return (
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>
            <Badge variant="secondary" className={`gap-1 ${className}`}>
              <Sparkles className="h-3 w-3" />
              Generated with AI
            </Badge>
          </TooltipTrigger>
          <TooltipContent className="max-w-xs">
            <p>{tooltipText}</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    );
  }

  // Icon variant
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <span className={`inline-flex items-center ${className}`}>
            <Sparkles className="h-3.5 w-3.5 text-muted-foreground" aria-label="AI-generated content" />
          </span>
        </TooltipTrigger>
        <TooltipContent className="max-w-xs">
          <p>{tooltipText}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
};
